language: swift
osx_image: xcode9.4
podfile: Example/CococaPods/Podfile
install:
  - bundle install
  - git clone https://github.com/yonaskolb/Mint.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout tags/0.11.3
  - make

script:
  - cd $TRAVIS_BUILD_DIR
  - cd Example/CocoaPods
  - mint bootstrap
  - mint run yonaskolb/XcodeGen
  - bundle exec pod install
  - xcodebuild clean build -sdk iphonesimulator -workspace Example.xcworkspace -scheme Example CODE_SIGNING_REQUIRED=NO
  - cd $TRAVIS_BUILD_DIR
  - cd Example/Carthage
  - mint bootstrap
  - mint run carthage bootstrap
  - mint run yonaskolb/XcodeGen
  - xcodebuild clean build -sdk iphonesimulator -project Example.xcodeproj -scheme Example CODE_SIGNING_REQUIRED=NO
