name: Example
options:
  bundleIdPrefix: com.myapp2
targets:
  Example:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [../Example]
    info:
      path: Info.plist
    dependencies:
      - package: Xcode9to10Preparation
packages:
  Xcode9to10Preparation:
    url: https://github.com/RomanPodymov/Xcode9to10Preparation
